name: preload_google_ads_example
description: "Demonstrates how to use the preload_google_ads plugin."

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  preload_google_ads:
    path: ../

  cupertino_icons: ^1.0.8
  change_app_package_name: ^1.5.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/

