name: preload_google_ads_example
description: "Demonstrates how to use the preload_google_ads plugin."
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  preload_google_ads:
    path: ../

  cupertino_icons: ^1.0.8

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launch_background"
  ios: true
  image_path: "assets/Preload Google Ad Logo.png"
  min_sdk_android: 21

flutter:

  uses-material-design: true

  assets:
    - assets/

